# 服务器端口
server:
  port: 80

web-socket:
  web-socket-server-ip-port: 94.191.27.230:80

spring:
  # 静态资源
  resources:
    # 静态资源查找路径
    static-locations: classpath:/static/,file:/data/OTA
    # 生产环境开启缓存缓存
    chain:
      cache: true
    # 开启 静态资源映射处理器
    #add-mappings: true

  # thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/static/html/
    suffix: .html
    cache: true