# 服务器端口
server:
  port: 83
  


web-socket:
  web-socket-server-ip-port: 10.112.98.226:80
  #web-socket-server-ip-port: 192.168.0.107:80

spring:
  # 热部署
  devtools:
    restart:
      #热部署生效
      enabled: true
      #设置重启的目录
      additional-paths: src/main/java
      #classpath目录下的WEB-INF文件夹内容修改不重启
      exclude: WEB-INF/**
  # 静态资源
  resources:
    # 静态资源查找路径
    static-locations: classpath:/static/,file:/data/OTA
    # 开发环境关闭缓存
    chain:
      cache: false
    # 开启 静态资源映射处理器
    #add-mappings: true


  # thymeleaf模板引擎
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false